// Interface automatically generated by schemas-to-ts

import { Media } from '../../shared/interfaces/Media';
import { Media_Plain } from '../../shared/interfaces/Media';

export interface Feature {
  title?: string;
  description?: string;
  media?: { data: Media };
  showLink?: boolean;
  newTab?: boolean;
  url?: string;
  text?: string;
}
export interface Feature_Plain {
  title?: string;
  description?: string;
  media?: Media_Plain;
  showLink?: boolean;
  newTab?: boolean;
  url?: string;
  text?: string;
}

export interface Feature_NoRelations {
  title?: string;
  description?: string;
  media?: number;
  showLink?: boolean;
  newTab?: boolean;
  url?: string;
  text?: string;
}

