// Interface automatically generated by schemas-to-ts

import { Media } from '../../shared/interfaces/Media';
import { Media_Plain } from '../../shared/interfaces/Media';

export interface HeroSection {
  introduction: string;
  Moto: string;
  SelfDescription: any;
  SelfPortait: { data: Media };
}
export interface HeroSection_Plain {
  introduction: string;
  Moto: string;
  SelfDescription: any;
  SelfPortait: Media_Plain;
}

export interface HeroSection_NoRelations {
  introduction: string;
  Moto: string;
  SelfDescription: any;
  SelfPortait: number;
}

