// Interface automatically generated by schemas-to-ts

import { Media } from '../../shared/interfaces/Media';
import { Media_Plain } from '../../shared/interfaces/Media';

export interface HeroSection {
  introduction: string;
  moto: string;
  selfDescription: any;
  selfPortrait: { data: Media };
}
export interface HeroSection_Plain {
  introduction: string;
  moto: string;
  selfDescription: any;
  selfPortrait: Media_Plain;
}

export interface HeroSection_NoRelations {
  introduction: string;
  moto: string;
  selfDescription: any;
  selfPortrait: number;
}

