// Interface automatically generated by schemas-to-ts

import { Link } from '../../links/interfaces/Link';
import { Link_Plain } from '../../links/interfaces/Link';
import { Link_NoRelations } from '../../links/interfaces/Link';

export enum Type {
  Alert = 'alert',
  Info = 'info',
  Warning = 'warning',}

export interface NotificationBanner {
  type: Type;
  heading: string;
  text: string;
  show?: boolean;
  link?: Link;
}
export interface NotificationBanner_Plain {
  type: Type;
  heading: string;
  text: string;
  show?: boolean;
  link?: Link_Plain;
}

export interface NotificationBanner_NoRelations {
  type: Type;
  heading: string;
  text: string;
  show?: boolean;
  link?: Link_NoRelations;
}

