// Interface automatically generated by schemas-to-ts

import { Media } from '../../shared/interfaces/Media';
import { Media_Plain } from '../../shared/interfaces/Media';

export interface Testimonial {
  picture: { data: Media };
  text: string;
  authorName: string;
}
export interface Testimonial_Plain {
  picture: Media_Plain;
  text: string;
  authorName: string;
}

export interface Testimonial_NoRelations {
  picture: number;
  text: string;
  authorName: string;
}

