// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../components/shared/interfaces/Media';
import { Category } from '../../../category/content-types/category/category';
import { Author } from '../../../author/content-types/author/author';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Media_Plain } from '../../../../components/shared/interfaces/Media';
import { Category_Plain } from '../../../category/content-types/category/category';
import { Author_Plain } from '../../../author/content-types/author/author';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Job {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    jobTitle?: string;
    description: any;
    fullDescription: any;
    start: Date;
    finish?: Date;
    fullTime?: boolean;
    company?: string;
    slug?: string;
    cover?: { data: Media };
    icon?: { data: Media };
    category?: { data: Category };
    authorsBio?: { data: Author };
    blocks?: any;
    seo?: Seo;
  };
}
export interface Job_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  jobTitle?: string;
  description: any;
  fullDescription: any;
  start: Date;
  finish?: Date;
  fullTime?: boolean;
  company?: string;
  slug?: string;
  cover?: Media_Plain;
  icon?: Media_Plain;
  category?: Category_Plain;
  authorsBio?: Author_Plain;
  blocks?: any;
  seo?: Seo_Plain;
}

export interface Job_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  jobTitle?: string;
  description: any;
  fullDescription: any;
  start: Date;
  finish?: Date;
  fullTime?: boolean;
  company?: string;
  slug?: string;
  cover?: number;
  icon?: number;
  category?: number;
  authorsBio?: number;
  blocks?: any;
  seo?: Seo_NoRelations;
}

export interface Job_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  jobTitle?: string;
  description: any;
  fullDescription: any;
  start: Date;
  finish?: Date;
  fullTime?: boolean;
  company?: string;
  slug?: string;
  cover?: AdminPanelRelationPropertyModification<Media_Plain>;
  icon?: AdminPanelRelationPropertyModification<Media_Plain>;
  category?: AdminPanelRelationPropertyModification<Category_Plain>;
  authorsBio?: AdminPanelRelationPropertyModification<Author_Plain>;
  blocks?: any;
  seo?: Seo_Plain;
}
