// Interface automatically generated by schemas-to-ts

export interface Job {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    JobTitle: string;
    JobDescription: any;
  };
}
export interface Job_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  JobTitle: string;
  JobDescription: any;
}

export interface Job_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  JobTitle: string;
  JobDescription: any;
}

export interface Job_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  JobTitle: string;
  JobDescription: any;
}
