// Interface automatically generated by schemas-to-ts

import { Article } from '../../../article/content-types/article/article';
import { Job } from '../../../job/content-types/job/job';
import { Article_Plain } from '../../../article/content-types/article/article';
import { Job_Plain } from '../../../job/content-types/job/job';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Category {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name?: string;
    slug?: string;
    articles: { data: Article[] };
    description?: string;
    jobs: { data: Job[] };
  };
}
export interface Category_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  slug?: string;
  articles: Article_Plain[];
  description?: string;
  jobs: Job_Plain[];
}

export interface Category_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  slug?: string;
  articles: number[];
  description?: string;
  jobs: number[];
}

export interface Category_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name?: string;
  slug?: string;
  articles: AdminPanelRelationPropertyModification<Article_Plain>;
  description?: string;
  jobs: AdminPanelRelationPropertyModification<Job_Plain>;
}
