// Interface automatically generated by schemas-to-ts

export enum Type {
  Primary = 'primary',
  Secondary = 'secondary',}

export interface ButtonLink {
  url?: string;
  newTab?: boolean;
  text?: string;
  type?: Type;
}
export interface ButtonLink_Plain {
  url?: string;
  newTab?: boolean;
  text?: string;
  type?: Type;
}

export interface ButtonLink_NoRelations {
  url?: string;
  newTab?: boolean;
  text?: string;
  type?: Type;
}

