// Interface automatically generated by schemas-to-ts

export enum TypeEnum {
  Primary = 'primary',
  Secondary = 'secondary',}

export interface Button {
  text?: string;
  type?: TypeEnum;
}
export interface Button_Plain {
  text?: string;
  type?: TypeEnum;
}

export interface Button_NoRelations {
  text?: string;
  type?: TypeEnum;
}

