// Interface automatically generated by schemas-to-ts

export interface Link {
  url: string;
  newTab?: boolean;
  text: string;
}
export interface Link_Plain {
  url: string;
  newTab?: boolean;
  text: string;
}

export interface Link_NoRelations {
  url: string;
  newTab?: boolean;
  text: string;
}

