// Interface automatically generated by schemas-to-ts

export enum Social {
  Linkedin = 'LINKEDIN',
  Youtube = 'YOUTUBE',
  Twitter = 'TWITTER',
  Discord = 'DISCORD',
  Website = 'WEBSITE',
  Github = 'GITHUB',
  Bsky = 'BSKY',}

export interface SocialLink {
  url: string;
  newTab?: boolean;
  text: string;
  social?: Social;
}
export interface SocialLink_Plain {
  url: string;
  newTab?: boolean;
  text: string;
  social?: Social;
}

export interface SocialLink_NoRelations {
  url: string;
  newTab?: boolean;
  text: string;
  social?: Social;
}

