// Interface automatically generated by schemas-to-ts

export enum SocialEnum {
  Youtube = 'YOUTUBE',
  Twitter = 'TWITTER',
  Discord = 'DISCORD',
  Website = 'WEBSITE',}

export interface SocialLink {
  url: string;
  newTab?: boolean;
  text: string;
  social?: SocialEnum;
}
export interface SocialLink_Plain {
  url: string;
  newTab?: boolean;
  text: string;
  social?: SocialEnum;
}

export interface SocialLink_NoRelations {
  url: string;
  newTab?: boolean;
  text: string;
  social?: SocialEnum;
}

