// Interface automatically generated by schemas-to-ts

export enum StatusEnum {
  Seen = 'seen',
  Contacted = 'contacted',
  Ignored = 'ignored',}

export interface LeadFormSubmission {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    email?: string;
    status?: StatusEnum;
  };
}
export interface LeadFormSubmission_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  email?: string;
  status?: StatusEnum;
}

export interface LeadFormSubmission_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  email?: string;
  status?: StatusEnum;
}

export interface LeadFormSubmission_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  email?: string;
  status?: StatusEnum;
}
