// Interface automatically generated by schemas-to-ts

import { Metadata } from '../../../../components/meta/interfaces/Metadata';
import { Metadata_Plain } from '../../../../components/meta/interfaces/Metadata';
import { Metadata_NoRelations } from '../../../../components/meta/interfaces/Metadata';

export interface Page {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    shortName?: string;
    metadata: Metadata;
    contentSections?: any;
    slug?: string;
    heading?: string;
    description?: string;
    locale: string;
    localizations?: { data: Page[] };
  };
}
export interface Page_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  shortName?: string;
  metadata: Metadata_Plain;
  contentSections?: any;
  slug?: string;
  heading?: string;
  description?: string;
  locale: string;
  localizations?: Page_Plain[];
}

export interface Page_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  shortName?: string;
  metadata: Metadata_NoRelations;
  contentSections?: any;
  slug?: string;
  heading?: string;
  description?: string;
  locale: string;
  localizations?: Page[];
}

export interface Page_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  shortName?: string;
  metadata: Metadata_Plain;
  contentSections?: any;
  slug?: string;
  heading?: string;
  description?: string;
  locale: string;
  localizations?: Page[];
}
