// Interface automatically generated by schemas-to-ts

export interface Metadata {
  metaTitle: string;
  metaDescription: string;
}
export interface Metadata_Plain {
  metaTitle: string;
  metaDescription: string;
}

export interface Metadata_NoRelations {
  metaTitle: string;
  metaDescription: string;
}

