// Interface automatically generated by schemas-to-ts

export interface Media {
  file?: { data: Media };
}
export interface Media_Plain {
  file?: Media_Plain;
}

export interface Media_NoRelations {
  file?: number;
}

