// Interface automatically generated by schemas-to-ts

export interface Quote {
  title?: string;
  body: string;
  author?: string;
}
export interface Quote_Plain {
  title?: string;
  body: string;
  author?: string;
}

export interface Quote_NoRelations {
  title?: string;
  body: string;
  author?: string;
}

