// Interface automatically generated by schemas-to-ts

export interface RichText {
  body?: string;
}
export interface RichText_Plain {
  body?: string;
}

export interface RichText_NoRelations {
  body?: string;
}

