// Interface automatically generated by schemas-to-ts

import { Media } from './Media';
import { Media_Plain } from './Media';

export interface Slider {
  files?: { data: Media[] };
}
export interface Slider_Plain {
  files?: Media_Plain[];
}

export interface Slider_NoRelations {
  files?: number[];
}

