// Interface automatically generated by schemas-to-ts

export interface VideoEmbed {
  url: string;
}
export interface VideoEmbed_Plain {
  url: string;
}

export interface VideoEmbed_NoRelations {
  url: string;
}

