// Interface automatically generated by schemas-to-ts

export interface Post {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    Title: string;
    PostText: any;
  };
}
export interface Post_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  PostText: any;
}

export interface Post_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  PostText: any;
}

export interface Post_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  Title: string;
  PostText: any;
}
