// Interface automatically generated by schemas-to-ts

import { Link } from '../../links/interfaces/Link';
import { ButtonLink } from '../../links/interfaces/ButtonLink';
import { Logo } from './Logo';
import { Link_Plain } from '../../links/interfaces/Link';
import { ButtonLink_Plain } from '../../links/interfaces/ButtonLink';
import { Logo_Plain } from './Logo';
import { Link_NoRelations } from '../../links/interfaces/Link';
import { ButtonLink_NoRelations } from '../../links/interfaces/ButtonLink';
import { Logo_NoRelations } from './Logo';

export interface Navbar {
  links: Link[];
  button?: ButtonLink;
  navbarLogo?: Logo;
}
export interface Navbar_Plain {
  links: Link_Plain[];
  button?: ButtonLink_Plain;
  navbarLogo?: Logo_Plain;
}

export interface Navbar_NoRelations {
  links: Link_NoRelations[];
  button?: ButtonLink_NoRelations;
  navbarLogo?: Logo_NoRelations;
}

