// Auto-generated Strapi types
// Generated on: 2025-11-28T16:42:54.697Z
// Do not edit this file manually

// Base Strapi types
export interface StrapiError {
  status: number;
  name: string;
  message: string;
  details: Record<string, unknown>;
}

export interface StrapiPagination {
  start: number;
  limit: number;
  total: number;
}

export interface StrapiCollectionMeta {
  pagination: StrapiPagination;
}

export interface StrapiSingleTypeMeta {
  availableLocales?: string[];
}

export interface StrapiMedia {
  id: number;
  documentId: string;
  name: string;
  alternativeText?: string | null;
  caption?: string | null;
  width: number;
  height: number;
  formats?: {
    [key: string]: {
      name: string;
      hash: string;
      ext: string;
      mime: string;
      path: string | null;
      width: number;
      height: number;
      size: number;
      sizeInBytes: number;
      url: string;
    };
  } | null;
  hash: string;
  ext: string;
  mime: string;
  size: number;
  url: string;
  previewUrl?: string | null;
  provider: string;
  provider_metadata?: any | null;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
}

export type StrapiRelation<T> = {
  id: number;
  documentId: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
} & T;

export type StrapiCollection<T> = Array<{
  id: number;
  documentId: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
} & T>;

export interface StrapiResponse<T> {
  data: T | null;
  error?: StrapiError;
}

export interface StrapiCollectionResponse<T> {
  data: T[] | null;
  meta: StrapiCollectionMeta;
  error?: StrapiError;
}

// Specific response types for single types
export interface StrapiSingleTypeResponse<T> {
  data: (T & { locale: string }) | null;
  meta?: StrapiSingleTypeMeta;
  error?: StrapiError;
}

export interface ElementsFeatureColumn {
  title: string;
  description?: string;
  icon: StrapiMedia;
}

export interface ElementsFeatureRow {
  title: string;
  description?: string;
  media: StrapiMedia;
  link?: LinksLink;
}

export interface ElementsFeature {
  title?: string;
  description?: string;
  media?: StrapiMedia;
  showLink?: boolean;
  newTab?: boolean;
  url?: string;
  text?: string;
}

export interface ElementsFooterSection {
  title?: string;
  links?: LinksLink[];
}

export interface ElementsHeroSection {
  introduction: string;
  moto: string;
  selfDescription: any;
  selfPortrait: StrapiMedia;
}

export interface ElementsLogos {
  title?: string;
  logo?: StrapiMedia;
}

export interface ElementsNotificationBanner {
  type: string;
  heading: string;
  text: string;
  show?: boolean;
  link?: LinksLink;
}

export interface ElementsPlan {
  name?: string;
  description?: string;
  isRecommended?: boolean;
  price?: number;
  pricePeriod?: string;
  product_features?: StrapiCollection<ProductFeature>;
}

export interface ElementsTestimonial {
  picture: StrapiMedia;
  text: string;
  authorName: string;
}

export interface LayoutFooter {
  footerLogo?: LayoutLogo;
  menuLinks?: LinksLink[];
  legalLinks?: LinksLink[];
  socialLinks?: LinksSocialLink[];
  categories?: StrapiCollection<Category>;
}

export interface LayoutLogo {
  logoImg?: StrapiMedia;
  logoText?: string;
}

export interface LayoutNavbar {
  links?: LinksLink[];
  button?: LinksButtonLink;
  navbarLogo?: LayoutLogo;
}

export interface LinksButtonLink {
  url?: string;
  newTab?: boolean;
  text?: string;
  type?: string;
}

export interface LinksButton {
  text?: string;
  type?: string;
}

export interface LinksLink {
  url: string;
  newTab?: boolean;
  text: string;
}

export interface LinksSocialLink {
  url: string;
  newTab?: boolean;
  text: string;
  social?: string;
}

export interface MetaMetadata {
  metaTitle: string;
  metaDescription: string;
}

export interface SectionsBottomActions {
  title?: string;
  buttons?: LinksButtonLink[];
  description?: string;
}

export interface SectionsFeatureColumnsGroup {
  features?: ElementsFeatureColumn[];
}

export interface SectionsFeatureRowsGroup {
  features?: ElementsFeatureRow[];
}

export interface SectionsFeatures {
  heading?: string;
  description?: string;
  feature?: ElementsFeature[];
}

export interface SectionsHeading {
  heading: string;
  description?: string;
}

export interface SectionsHero {
  title: string;
  description: string;
  picture: StrapiMedia;
  buttons?: LinksButtonLink[];
}

export interface SectionsLargeVideo {
  title?: string;
  description?: string;
  video: StrapiMedia;
  poster?: StrapiMedia;
}

export interface SectionsLeadForm {
  title?: string;
  emailPlaceholder?: string;
  submitButton?: LinksButton;
  location?: string;
  description?: string;
}

export interface SectionsPricing {
  title?: string;
  plans?: ElementsPlan[];
}

export interface SectionsRichText {
  content?: string;
}

export interface SectionsTestimonialsGroup {
  title?: string;
  description?: string;
  testimonials?: ElementsTestimonial[];
}

export interface SharedMedia {
  file?: StrapiMedia;
}

export interface SharedQuote {
  title?: string;
  body: string;
  author?: string;
}

export interface SharedRichText {
  body?: string;
}

export interface SharedSeo {
  metaTitle: string;
  metaDescription: string;
  shareImage?: StrapiMedia;
}

export interface SharedSlider {
  files?: StrapiMedia[];
}

export interface SharedVideoEmbed {
  url: string;
}

export interface Article {
  id: number;
  documentId: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  title?: string;
  description: string;
  slug?: string;
  cover?: StrapiMedia;
  category?: StrapiRelation<Category>;
  blocks?: any[];
  authorsBio?: StrapiRelation<Author>;
  seo?: SharedSeo;
}

export interface Author {
  id: number;
  documentId: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  name?: string;
  avatar?: StrapiMedia;
  email?: string;
  articles?: StrapiCollection<Article>;
}

export interface Category {
  id: number;
  documentId: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  name?: string;
  slug?: string;
  articles?: StrapiCollection<Article>;
  description?: string;
}

export interface Global {
  id: number;
  documentId: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  metadata?: MetaMetadata;
  hero_section?: ElementsHeroSection;
  favicon: StrapiMedia;
  notificationBanner?: ElementsNotificationBanner;
  navbar?: LayoutNavbar;
  footer?: LayoutFooter;
  cv?: StrapiMedia;
}

export interface LeadFormSubmission {
  id: number;
  documentId: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  email?: string;
  status?: string;
}

export interface Page {
  id: number;
  documentId: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  shortName?: string;
  metadata: MetaMetadata;
  contentSections?: any[];
  slug?: string;
  heading?: string;
  description?: string;
}

export interface Post {
  id: number;
  documentId: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  Title: string;
  PostText: any;
}

export interface ProductFeature {
  id: number;
  documentId: string;
  createdAt: string;
  updatedAt: string;
  publishedAt: string;
  name: string;
}

// Specific response types
export type ArticleResponse = StrapiCollectionResponse<Article>;
export type ArticleSingleResponse = StrapiResponse<Article>;
export type AuthorResponse = StrapiCollectionResponse<Author>;
export type AuthorSingleResponse = StrapiResponse<Author>;
export type CategoryResponse = StrapiCollectionResponse<Category>;
export type CategorySingleResponse = StrapiResponse<Category>;
export type GlobalResponse = StrapiSingleTypeResponse<Global>;
export type LeadFormSubmissionResponse = StrapiCollectionResponse<LeadFormSubmission>;
export type LeadFormSubmissionSingleResponse = StrapiResponse<LeadFormSubmission>;
export type PageResponse = StrapiCollectionResponse<Page>;
export type PageSingleResponse = StrapiResponse<Page>;
export type PostResponse = StrapiCollectionResponse<Post>;
export type PostSingleResponse = StrapiResponse<Post>;
export type ProductFeatureResponse = StrapiCollectionResponse<ProductFeature>;
export type ProductFeatureSingleResponse = StrapiResponse<ProductFeature>;
