// Interface automatically generated by schemas-to-ts

export interface Skills {
  skill?: string;
}
export interface Skills_Plain {
  skill?: string;
}

export interface Skills_NoRelations {
  skill?: string;
}

