// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../components/shared/interfaces/Media';
import { Category } from '../../../category/content-types/category/category';
import { Author } from '../../../author/content-types/author/author';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Media_Plain } from '../../../../components/shared/interfaces/Media';
import { Category_Plain } from '../../../category/content-types/category/category';
import { Author_Plain } from '../../../author/content-types/author/author';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Article {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    description: string;
    slug?: string;
    cover?: { data: Media };
    category?: { data: Category };
    blocks?: any;
    authorsBio?: { data: Author };
    seo?: Seo;
  };
}
export interface Article_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description: string;
  slug?: string;
  cover?: Media_Plain;
  category?: Category_Plain;
  blocks?: any;
  authorsBio?: Author_Plain;
  seo?: Seo_Plain;
}

export interface Article_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description: string;
  slug?: string;
  cover?: number;
  category?: number;
  blocks?: any;
  authorsBio?: number;
  seo?: Seo_NoRelations;
}

export interface Article_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  description: string;
  slug?: string;
  cover?: AdminPanelRelationPropertyModification<Media_Plain>;
  category?: AdminPanelRelationPropertyModification<Category_Plain>;
  blocks?: any;
  authorsBio?: AdminPanelRelationPropertyModification<Author_Plain>;
  seo?: Seo_Plain;
}
