// Interface automatically generated by schemas-to-ts

import { FeatureRow } from '../../elements/interfaces/FeatureRow';
import { FeatureRow_Plain } from '../../elements/interfaces/FeatureRow';
import { FeatureRow_NoRelations } from '../../elements/interfaces/FeatureRow';

export interface FeatureRowsGroup {
  features: FeatureRow[];
}
export interface FeatureRowsGroup_Plain {
  features: FeatureRow_Plain[];
}

export interface FeatureRowsGroup_NoRelations {
  features: FeatureRow_NoRelations[];
}

