// Interface automatically generated by schemas-to-ts

export interface Heading {
  heading: string;
  description?: string;
}
export interface Heading_Plain {
  heading: string;
  description?: string;
}

export interface Heading_NoRelations {
  heading: string;
  description?: string;
}

