// Interface automatically generated by schemas-to-ts

import { Media } from '../../shared/interfaces/Media';
import { ButtonLink } from '../../links/interfaces/ButtonLink';
import { Media_Plain } from '../../shared/interfaces/Media';
import { ButtonLink_Plain } from '../../links/interfaces/ButtonLink';
import { ButtonLink_NoRelations } from '../../links/interfaces/ButtonLink';

export interface Hero {
  title: string;
  description: string;
  picture: { data: Media };
  buttons: ButtonLink[];
}
export interface Hero_Plain {
  title: string;
  description: string;
  picture: Media_Plain;
  buttons: ButtonLink_Plain[];
}

export interface Hero_NoRelations {
  title: string;
  description: string;
  picture: number;
  buttons: ButtonLink_NoRelations[];
}

