// Interface automatically generated by schemas-to-ts

import { Plan } from '../../elements/interfaces/Plan';
import { Plan_Plain } from '../../elements/interfaces/Plan';
import { Plan_NoRelations } from '../../elements/interfaces/Plan';

export interface Pricing {
  title?: string;
  plans: Plan[];
}
export interface Pricing_Plain {
  title?: string;
  plans: Plan_Plain[];
}

export interface Pricing_NoRelations {
  title?: string;
  plans: Plan_NoRelations[];
}

