// Interface automatically generated by schemas-to-ts

export interface RichText {
  content?: string;
}
export interface RichText_Plain {
  content?: string;
}

export interface RichText_NoRelations {
  content?: string;
}

