// Interface automatically generated by schemas-to-ts

import { Testimonial } from '../../elements/interfaces/Testimonial';
import { Testimonial_Plain } from '../../elements/interfaces/Testimonial';
import { Testimonial_NoRelations } from '../../elements/interfaces/Testimonial';

export interface TestimonialsGroup {
  title?: string;
  description?: string;
  testimonials: Testimonial[];
}
export interface TestimonialsGroup_Plain {
  title?: string;
  description?: string;
  testimonials: Testimonial_Plain[];
}

export interface TestimonialsGroup_NoRelations {
  title?: string;
  description?: string;
  testimonials: Testimonial_NoRelations[];
}

