// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../components/shared/interfaces/Media';
import { Media_Plain } from '../../../../components/shared/interfaces/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Project {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    description: any;
    fullDescription: any;
    slug: string;
    linkToApp: string;
    linkToRepo: string;
    cover?: { data: Media };
    icon?: { data: Media };
  };
}
export interface Project_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: any;
  fullDescription: any;
  slug: string;
  linkToApp: string;
  linkToRepo: string;
  cover?: Media_Plain;
  icon?: Media_Plain;
}

export interface Project_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: any;
  fullDescription: any;
  slug: string;
  linkToApp: string;
  linkToRepo: string;
  cover?: number;
  icon?: number;
}

export interface Project_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  description: any;
  fullDescription: any;
  slug: string;
  linkToApp: string;
  linkToRepo: string;
  cover?: AdminPanelRelationPropertyModification<Media_Plain>;
  icon?: AdminPanelRelationPropertyModification<Media_Plain>;
}
